#ifndef ERRORCODE_H
#define ERRORCODE_H

typedef enum {
    ERR_OK = 0,
    ERR_LEXER_UNKONW_CHAR,
    ERROR_PARSER_CLOSE_PAREN_UNBALANCED,
    ERROR_PARSER_OPEN_PAREN_UNBALANCED,
    ERROR_PARSER_MISSING_OPERAND,
    ERROR_MEMORY_ALLOCATION
}ErrorCode;

#endif